### ISSUE TITLE
Traducir la interfaz a otros idiomas

### ISSUE THREAD

**Issue by PedBerTor** [PedBerTor/decide-ganimedes-cabina#11]
_Issue recreada debido a que la original fue borrada_

Internacionalizar el sistema de forma que esté disponible en español, inglés y catalán.

**Comment by javtoronun** [comment]
Ya está implementado este cambio.

**Comment by PedBerTor** [comment]
Lo he probado y hay dos mensajes que no se traducen (siempre aparecen en inglés):

1. Mensaje de "Cambiar idioma" en la barra superior.
2. Mensaje de "Iniciar sesión" en el botón de login.

Échale un ojo.

**Comment by javtoronun** [comment]
Ya esta terminado pero siempre que se realice un clone del repositorio tienes que ejecutar el siguiente comando en el terminal (administrador) para que se actualicen todos los mensajes traducidos.
       1. Accedes a la ruta del donde esta alojado el proyecto
       2. django-admin compilemessages
Estaría bien crear un script que incluya el makemigrations, migrate, el comando anterior de cara al M2.

**Comment by PedBerTor** [comment]
Sí, el script está en proceso de creación. Introduciré ese comando al final del mismo (después de migrate). Cierro el issue y marco la tarea como terminada.
