### ISSUE TITLE
Diseño único

### ISSUE THREAD

**Issue by javsanbel2** [PedBerTor/decide-ganimedes-cabina#13]
_Issue recreada debido a que la original fue borrada_

Utilizar un estilo de diseño único entre todos los módulos de la aplicación Decide para aportar una vista de aplicación uniforme. Para conseguir esto, podemos considerar lo siguiente:

- Utilizar un framework de diseño para sitios web como Bootstrap, Material Design...
- Crear una ruta/carpeta única para todos los módulos (grupos de decide) en los que estén los parámetros del diseño. Por ejemplo, podríamos crear una carpeta padre que se llame 'design' y dentro de esa carpeta crear una carpeta general para parametros de diseño generales y una carpeta por cada modulo para paginas únicas.

**Comment by PedBerTor** [comment]
_Issue recreada debido a que la original fue borrada_

Issue aceptada por los coordinadores de los subsistemas implicados. Se va a crear un gremio formado por un integrante de cada subsistema implicado. Escalo la issue a tarea y queda asignada a @javsanbel2.

**Comment by javsanbel2** [comment]
Terminado.

**Comment by PedBerTor** [comment]
Ya lo he probado. Marco la el Issue como cerrado y la Tarea como terminada. Buen trabajo @javsanbel2.
