### ISSUE TITLE
Añadir votación por voz

### ISSUE THREAD

**Issue by javsanbel2** [PedBerTor/decide-ganimedes-cabina#14]
Que una persona pueda escuchar las preguntas y las respuestas por el robot de Google si lo desea y, además, pueda responder cada pregunta por voz y se seleccione automáticamente.

**Comment by javsanbel2** [comment]
Terminado.

**Comment by PedBerTor** [comment]
Ya he probado la implementación de esta tarea y es correcta. Marco el Issue como cerrado y la Tarea como completada. Buen trabajo @javsanbel2.
