### ISSUE TITLE
Creación de una votación

### ISSUE THREAD

**Issue by javtoronun** [PedBerTor/decide-ganimedes-cabina#16]
Una vez autenticado como superusuario se produce un error cuando accedemos a voting.
Error devuelto:
cursor "_django_curs_14948_1" does not exist

**Comment by PedBerTor** [comment]
Creo que el error se debe a que nuestra versión del fork está desactualizada con respecto a Decide-Ganimedes. Voy a realizar un pull request hacia nuestro repositorio y si no funciona escalo esta issue a Decide-Ganimedes.

**Comment by PedBerTor** [comment]
Ya hemos traido los cambios del servidor. Pruébalo en tu máquina.

**Comment by javtoronun** [comment]
Correcto, era por que teníamos una versión anterior. 
Muchas gracias Pedro.

**Comment by PedBerTor** [comment]
Perfecto, procedo a cerrar la incidencia.
