### ISSUE TITLE
Diseño de votaciones con varias preguntas

### ISSUE THREAD

**Issue by PedBerTor** [PedBerTor/decide-ganimedes-cabina#17]
En las votaciones con varias preguntas solo la primera pregunta aparece centrada, el resto aparecen desplazadas a la izquierda

**Comment by PedBerTor** [comment]
Me he fijado que la descripción de las votaciones nunca se utiliza. Estaría bien que apareciera encima de las preguntas de la votación.

**Comment by javsanbel2** [comment]
Resueltas las dos issues

**Comment by PedBerTor** [comment]
Incidencia resuelta. Cierro el Issue. Buen trabajo @javsanbel2.
