### ISSUE TITLE
Preguntas con al menos dos opciones

### ISSUE THREAD

**Issue by PedBerTor** [PedBerTor/decide-ganimedes-cabina#19]
Forzar a que las preguntas de las votaciones tengan, al menos, dos opciones de respuesta. No tiene sentido que se puedan crear preguntas con una sola respuesta o sin respuesta.

**Comment by PedBerTor** [comment]
Propongo a @santyago723 para realizar esta tarea. Me mantengo a la espera de confirmación.

**Comment by santyago723** [comment]
Vale, estoy dispuesto a realizar esta propuesta.

**Comment by PedBerTor** [comment]
Perfecto, escalo la Issue a Tarea y queda asignada a @santyago723.

**Comment by santyago723** [comment]
He hecho commit de la implementación del cambio, además he añadido comentarios indicando los bloques de autoenumeración en los métodos save de Question y OptionQuestion. Solo falta probar el cambio.

**Comment by santyago723** [comment]
He hecho commit de la implementación del cambio, además he añadido comentarios indicando los bloques de autoenumeración en los métodos save de Question y OptionQuestion. Solo falta probar el cambio.

**Comment by PedBerTor** [comment]
Perfecto, esta tarde lo pruebo.

**Comment by PedBerTor** [comment]
La implementación del cambio es incorrecta:
- Cuando se intenta crear una pregunta sin opciones el formulario te devuelve a la pagina de inicio.
- Cuando se intenta crear una pregunta con opciones se obtiene un error en el save de Question.

**Comment by santyago723** [comment]
He eliminado la opción de borrar las opciones de las preguntas

**Comment by PedBerTor** [comment]
Ya lo he probado y funciona bien. He hablado con otros coordinadores sobre eliminar la opcion de borrar las opciones y estan de acuerdo. Buen trabajo, @santyago723, cierro el Issue y marco la tarea como completada.

**Comment by PedBerTor** [comment]
Sin problemas @santyago723, es más importante el otro cambio. Voy a marcar la Tarea como cancelada y cierro el Issue.
