### ISSUE TITLE
Controlar correo y contraseña en el login de cabina

### ISSUE THREAD

**Issue by javtoronun** [PedBerTor/decide-ganimedes-cabina#21]
Ahora mismo tras el cambio de @santyago723 en el login de cabina se controla que a la hora de acceder a la votación. esta tenga (al menos) una pregunta,pero no se controla que el usuario introduzca un correo electrónico y una contraseña. Esto se traduce en que si intentamos acceder a una votación sin preguntas dejando los inputs en blanco, el mensaje de error que nos aparece es que la votación no tiene preguntas, cuando debería indicarse al usuario que tiene que introducir un correo y una contraseña.

**Comment by santyago723** [comment]
He implementado la comprobación, solo falta la prueba de esta, la cual se encuentra en la función decideLogin()

**Comment by PedBerTor** [comment]
Está implementado correctamente. Cierro el Issue y marco la Tarea como completada. Buen trabajo @santyago723.
