### ISSUE TITLE
Error al comenzar votación debido a internacionalización

### ISSUE THREAD

**Issue by PedBerTor** [PedBerTor/decide-ganimedes-cabina#26]
Para generar la clave pública de ElGamal, hay que comenzar la votación. El método que se encarga de ello genera una excepción, por lo que no se puede generar la clave pública de ElGamal y la cabina se para al intentar votar. Esta incidencia debe ser solucionada de cara al milestone 3.

**Comment by PedBerTor** [comment]
Error:
```
TypeError at /admin/voting/voting/ -> list indices must be integers or slices, not str
Exception Location: | C:\Users\pedro\decide-ganimedes-cabina\decide\voting\models.py in create_pubkey, line 38
```
En concreto esa línea accede a un mapa que contiene los tres parámetros que forman la clave pública ElGamal. Ese mapa es el resultado de llamar a la función post de Mixnet. Parece ser que no devuelve un mapa sino una lista, por lo que al intentar acceder por el nombre de la clave da error.
```
data = {
    "voting": self.id,
    "auths": [ {"name": a.name, "url": a.url} for a in self.auths.all() ],
}
key = mods.post('mixnet', baseurl=auth.url, json=data)
pk = Key(p=key["p"], g=key["g"], y=key["y"]) <-- ***********ERROR************
```

**Comment by PedBerTor** [comment]
Cuando se llama en create_pubkey (voting/models.py) para conseguir la clave publica como un diccionario, devuelve vacío:
```
pk = Key(p=key["p"], g=key["g"], y=key["y"]) <-- []
```

**Comment by PedBerTor** [comment]
Si se llama en create_pubkey (voting/models.py) para conseguir la clave publica, habiendo creado una mixnet (asociada a la votación) previamente, el método post devuelve:
```
pk = Key(p=key["p"], g=key["g"], y=key["y"]) <-- [{'voting_id': 1, 'auths': [{'name': 'auth1', 'url': 'http://localhost:8000', 'me': True}], 'pubkey': None}]
```
**Sigue sin generar la clave pública**

**Comment by PedBerTor** [comment]
Si se introduce en la mixnet creada anteriormente una clave pública ElGamal, el método post devuelve todos los campos.
```
[{'voting_id': 1, 'auths': [{'name': 'auth1', 'url': 'http://localhost:8000', 'me': True}], 'pubkey': {'p': 2081, 'g': 2060, 'y': 238}}]
```
Aun así, no se como es que se pretende acceder a los datos de la clave como si fuera un diccionario, ya que son dos diccionarios, uno dentro del otro.

**Comment by PedBerTor** [comment]
Si se modifica la linea de código que obtiene la clave, la votación se inicia correctamente.
**NORMAL**
```
pk = Key(p=key["p"], g=key["g"], y=key["y"])
```
**MODIFICADA**
```
pk = Key(p=key[0]["pubkey"]["p"], g=key[0]["pubkey"]["g"], y=key[0]["pubkey"]["y"])
```
![tempsnip](https://user-images.githubusercontent.com/16528784/50296850-a8bda480-047b-11e9-9391-38fa2ca38dbf.png)

**Comment by PedBerTor** [comment]
Tras la modificación anterior, el cifrado funciona correctamente. Por ejemplo, el cifrado del primer voto da como resultado:
`
data["votes"][0]["a"] = 1662 | data["votes"][0]["b"] = 935
`

**Comment by PedBerTor** [comment]
Tal y como se ha expuesto en los comentarios anteriores, parece ser que el fallo reside en la implementación de la función "create_pub_key" (voting/booth.html). Voy a comentarlo al resto de coordinadores a ver que opinan del tema, ya que me extraña que nadie haya reportado este error.

**Comment by PedBerTor** [comment]
Tras comentarlo con el resto de coordinadores, en la versión de Decide-Ganimedes no encuentran este error, han replicado según las intrucciones de esta Incidencia y les funciona correctamente.

**Comment by PedBerTor** [comment]
El error es derivado de la internacionalización realizada por @javtoronun, la cual utiliza prefijos en la URL. Debido a esto, los métodos post de las APIs no funcionan y al intentar conseguir la clave pública da el error. Voy a cambiar el título de la Incidencia y asignar su solución a @javtoronun. Habría que realizar la internacionalización sin prefijos.

**Comment by javtoronun** [comment]
Ya se ha solucionado el problema.

**Comment by PedBerTor** [comment]
Incidencia solucionada. Buen trabajo @javtoronun.
