### ISSUE TITLE
Listado de votaciones abiertas

### ISSUE THREAD

**Issue by PedBerTor** [PedBerTor/decide-ganimedes-cabina#39]
Desde decide-ganimedes se necesita un grupo voluntario para implementar un listado de votaciones abiertas. Las votaciones abiertas son aquellas con fecha de inicio no nula y fecha de fin nula. Se debe poder acceder a la cabina de cada votación. Esta tarea queda asignada a @santyago723.

**Comment by santyago723** [comment]
He terminado la implementación del listado, solo falta que  @javtoronun internacionalice los mensajes

**Comment by PedBerTor** [comment]
Ya he probado la implementación @santyago723 y es correcta. Añado a @javtoronun a la Tarea para que implemente la internacionalización de los mensajes.

**Comment by javtoronun** [comment]
Acabo de terminar la internacionalización en los distintos idiomas.

**Comment by PedBerTor** [comment]
Hay un fallo en la traducción de "Votaciones Abiertas" en catalán. Está traducido como "Votatge Obert", cuando la traudcción correcta es "votacions obertes".

**Comment by PedBerTor** [comment]
También estaría bien cambiar de "Open Votings" a "Open votings".

**Comment by PedBerTor** [comment]
También en uno de los mensajes de control de acceso a cabina (uno de los situados en el bloque _if/else_) aparece _vote_ cuando debería aparecer _voting_.

**Comment by PedBerTor** [comment]
Ya lo he probado y la implementación es correcta. Marco la Tarea como completada y cierro la Issue. Buen trabajo @santyago723 y @javtoronun.
