### ISSUE TITLE
Despliegue del proyecto

### ISSUE THREAD

**Issue by PedBerTor** [PedBerTor/decide-ganimedes-cabina#4]
Clonar el repositorio y desplegarlo.

**Comment by javsanbel2** [comment]
Mi parte de la tarea está terminada.

**Comment by PedBerTor** [comment]
Mi parte de la tarea está terminada.

**Comment by jato97** [comment]
Mi parte de la tarea está terminada.

**Comment by santyago723** [comment]
Mi parte de la tarea está terminada.

**Comment by PedBerTor** [comment]
Tarea completada.
