### ISSUE TITLE
Texto de ayuda para cada pregunta

### ISSUE THREAD

**Issue by PedBerTor** [PedBerTor/decide-ganimedes-cabina#6]
Esta mejora consiste en añadir un atributo nuevo a Question en los modelos del subsistema Voting. Este atributo, llamado "help_text", es opcional y, en caso de que exista, permitirá mostrar un pop-up que se situará al lado de la pregunta a la que esté asociado, indicando algún tipo de consideración a tener en cuenta a la hora de responder dicha pregunta.

**Comment by PedBerTor** [comment]
Asigno la tarea a @javtoronun.

**Comment by javtoronun** [comment]
Revisalo, lo acabo de pushear. Tan solo quedaría implementar el diseño del pop up.

**Comment by PedBerTor** [comment]
Esta muy bien. Tan solo queda implementar el diseño del "globo", asigno a @javsanbel2 para esa tarea.

**Comment by javsanbel2** [comment]
Ya está implementado el diseño.

**Comment by PedBerTor** [comment]
Ya lo he probado, la implementación es correcta. Marco el Issue como cerrado y la Tarea como completada. Buen trabajo @javtoronun y @javsanbel2.
